### ISSUE TITLE
Build process should copy extra static files

### ISSUE THREAD

**Issue by imaustink** [bit-docs/bit-docs-generate-html#39]
In addition to copying the bundles, we should also copy static files from the `/extra` folder of the template plugin. This would be useful for things like image and `Worker` files.

The change should probably happen here: https://github.com/bit-docs/bit-docs-generate-html/blob/master/site/default/static/build.js#L41

Justin brought this up here: https://bitovi.slack.com/archives/C09R50SAE/p1499289208210257

**Comment by chasenlehara** [comment]
@justinbmeyer There’s already code for copying static files into the build: https://github.com/bit-docs/bit-docs-generate-html/blob/0219141c0d2ae7e13c43f3ba11eadf165a23bcc1/build/static_dist.js#L82-L84

Would it be best to just use that instead of modifying the code mentioned in this issue’s description?

**Comment by justinbmeyer** [comment]
@chasenlehara yeah, probably.  Thought we should make it so static can be an array of sources.  Lets talk about this at some point.

**Comment by chasenlehara** [comment]
https://github.com/bit-docs/bit-docs-generate-html/pull/41
